# Generated by Django 5.2.3 on 2025-11-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0004_paiement_numero_client_paiement_numero_entreprise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='Paiement_datechoisi',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='Paiement_montantchoisi',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='Paiement_type',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='numero_client',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='numero_entreprise',
        ),
    ]
