# Generated by Django 5.2.3 on 2025-11-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0005_remove_paiement_paiement_datechoisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='Paiement_datechoisi',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='Paiement_montantchoisi',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='Paiement_type',
            field=models.CharField(blank=True, choices=[('mensuel', 'Mensuel'), ('comptant', 'Comptant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_client',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_entreprise',
            field=models.CharField(blank=True, default='0340000001', max_length=20, null=True),
        ),
    ]
